# mapr-jobtracker installation
- hosts: mapr-jobtracker
  gather_facts: true
  sudo: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-jobtracker"

    - name: Copy ssh keygen script
      copy: src=./files/root_ssh_keygen.sh dest=/tmp/

    - name: Change Permission 
      shell: chmod 777 /tmp/root_ssh_keygen.sh 

    - name: Execute ssh keygen script
      shell: /tmp/root_ssh_keygen.sh

    - name: Fetch authorized_key file
      fetch: src=/root/.ssh/id_rsa.pub dest=./files/root_authorized_keys_new flat=yes

    - name: Copy ssh keygen script
      copy: src=./files/mapr_ssh_keygen.sh dest=/tmp/

    - name: Change Permission 
      shell: chmod 777 /tmp/mapr_ssh_keygen.sh 

    - name: Execute ssh keygen script
      shell: /tmp/mapr_ssh_keygen.sh

    - name: Fetch authorized_key file
      fetch: src=/home/mapr/.ssh/id_rsa.pub  dest=./files/mapr_authorized_keys_new flat=yes

# mapr-cldb installation 
- hosts: mapr-cldb
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-cldb"

# mapr-zookeeper installation
- hosts: mapr-zookeeper
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-zookeeper"

# mapr-nfs installation
- hosts: mapr-nfs
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-nfs"

#mapr-webserver installation
- hosts: mapr-webserver
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-webserver"

# mapr-fileserver installation
- hosts: mapr-fileserver
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-fileserver"

# mapr-resourcemanager installation
- hosts: mapr-resourcemanager
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-resourcemanager"

# mapr-historyserver installation
- hosts: mapr-historyserver
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-historyserver"

# mapr-nodemanager installation
- hosts: mapr-nodemanager
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-nodemanager"

# mapr-tasktracker installation
- hosts: mapr-tasktracker
  gather_facts: true
  tasks:
    - include: pkg_install.yaml pkg_name="mapr-tasktracker"


- hosts: allnodes
  gather_facts: true
  sudo: true
  tasks:
    - name: Send job tracker root authorized_key file
      copy: src=./files/root_authorized_keys_new dest=/root/.ssh/root_authorized_keys_new

    - name: Add job tracker root authorized_key to existing file
      authorized_key: user=root key="{{ lookup('file', './files/root_authorized_keys_new') }}"

    - name: Send mapr authorized_key file to newnode
      copy: src=./files/mapr_authorized_keys_new dest=/home/mapr/.ssh/mapr_authorized_keys_new

    - name: Add authorized_key to existing file
      authorized_key: user=mapr key="{{ lookup('file', './files/mapr_authorized_keys_new') }}"

    - name: /opt/mapr/conf/env.sh configuration
      lineinfile: dest=/opt/mapr/conf/env.sh
         insertbefore='^#set JAVA_HOME'
         line="export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64"

    - name: /opt/mapr/conf/env.sh configuration
      lineinfile: dest=/opt/mapr/conf/env.sh
         insertbefore='^#set JAVA_HOME'
         line="export MAPR_HOME=/opt/mapr"

    - name: /opt/mapr/conf/env.sh configuration
      lineinfile: dest=/opt/mapr/conf/env.sh
         insertbefore='^#set JAVA_HOME'
         line="export MAPR_SUBNETS={{ subnet }} "

    - name: /opt/mapr/conf/env.sh configuration
      lineinfile: dest=/opt/mapr/conf/env.sh
         insertbefore='^#set JAVA_HOME'
         line="export MAPR_USER=mapr"

    - name: /opt/mapr/conf/env.sh configuration
      lineinfile: dest=/opt/mapr/conf/env.sh
         insertbefore='^#set JAVA_HOME'
         line="export MAPR_ECOSYSTEM_LOGIN_OPTS=*hybrid*"

    - name: Generate configure.sh script
      copy: src=./files/cmd.sh dest=/tmp/cmd.sh

    - name: Change Permission 
      shell: chmod 777 /tmp/cmd.sh

    - name: Configure the node 
      shell: /tmp/cmd.sh


    - name: Disk configuration
      shell: lsblk --noheadings --list | gawk '{if( $6 != "rom" && $3 == 0 ) print $1}' | awk '{print $1}' | cut -c1-3 | uniq -c | awk '{if( $1 == 1) print $2}' |  nl -s /dev/ |  cut -c7-15 > /tmp/disks.txt

#lsblk --noheadings --list | gawk '{if( $6 != "rom") print $1}' | awk '{print $1}' | cut -c1-3 | uniq -c | awk '{if( $1 == 1) print $2}' |  nl -s /dev/ |  cut -c7-15  > /tmp/disks.txt

    - name: Disk configuration
      shell: /opt/mapr/server/disksetup -F /tmp/disks.txt

- hosts: localhost 
  gather_facts: true
  sudo: true
  vars:
    path1: "{{lookup('pipe', 'pwd')}}"
  tasks:
    - name: Script to add root permisssions
      command: python {{ path1 }}/files/root_permissions.py


#----------------------------------------------------------------------------------------------



#---------------------------------------------------------------------------------------------

- hosts: mapr-zookeeper
  gather_facts: true
  sudo: true
  tasks:
    - name: Start zookeeper service
      shell: service mapr-zookeeper restart

    - include: pkg_status_check.yaml pkg_name="mapr-warden"

    - name: mapr-zookeeper qstatus
      shell: service mapr-zookeeper qstatus
      register: status7

    - name : mapr-zookeeper qstatus
      debug: var=status7.stdout

- hosts: mapr-cldb
  gather_facts: true
  sudo: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"
    - pause: minutes=3

    - name: mapr-cldb status
      shell: service mapr-cldb status
      register: status1

    - name : mapr-cldb status
      debug: var=status1.stdout


- hosts: mapr-nfs
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-webserver
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-fileserver
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-jobtracker
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-resourcemanager
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-historyserver
  gather_facts: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"


- hosts: mapr-nodemanager
  gather_facts: true
  sudo: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"
    - pause: minutes=3

    - name: mapr-mfs status
      shell: service mapr-mfs status
      register: status4

    - name : mapr-mfs status
      debug: var=status4.stdout


- hosts: mapr-tasktracker
  gather_facts: true
  sudo: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"
    - pause: minutes=3

    - name: mapr-mfs status
      shell: service mapr-mfs status
      register: status4

    - name : mapr-mfs status
      debug: var=status4.stdout


- hosts: mapr-fileserver
  gather_facts: true
  sudo: true
  tasks:
    - include: pkg_status_check.yaml pkg_name="mapr-warden"
    - pause: minutes=3

    - name: mapr-mfs status
      shell: service mapr-mfs status
      register: status4

    - name : mapr-mfs status
      debug: var=status4.stdout

