- hosts: squid3
  gather_facts: true
  sudo: true
  roles:
   - {role: install_squid, subnet: "{{subnet}}" }


- hosts: localhost
  gather_facts: true
  sudo: true
  vars:
    path: "{{lookup('pipe', 'pwd')}}"
  tasks:
    - include: pkg_install.yaml pkg_name="python-pip"

    - name: Install configobj
      pip: name=configobj state=present

    - name: Script to generate proxy url, create ntp settings & create configure.sh
      command: python {{ path }}/files/setup_preperation.py {{ path }} {{ cluster_name }}


- hosts: allnodes
  gather_facts: true
  sudo: true
  roles:
   - prerequisites


- hosts: ntp-server
  gather_facts: true
  sudo: true
  roles:
   - ntp_server_config


- hosts: allnodes
  gather_facts: true
  sudo: true
  roles:
   - ntp_client_config

